### ISSUE TITLE
Read custom segdb triplets and segments from config file

### ISSUE THREAD

**Issue by jithenece** [MHubAI/mhubio#3]
I tried to add the custom segdb but it did not work for me. 

Could you check if below logic 
1. Do we need to process as dictionary [here](https://github.com/MHubAI/mhubio/blob/main/mhubio/core/Config.py#L143)?

`for seg_id, seg_data in self._config['segdb']['segments']:`

to 

`for seg_id, seg_data in self._config['segdb']['segments'].items():`

2. Change the example to use segments instead of segmentations [here](https://github.com/MHubAI/documentation/blob/main/documentation/mhubio/the_mhubio_config_file.md#segdb-customization)?

```

segdb:
  triplets:
    MY_CUSTOM_TRIPLET:
      code: 123
      meaning: custom code
  segmentations:
    MY_CUSTOM_SEGMENTATION:
      name: custom segmentation
      category: C_BODY_STRUCTURE
      type: MY_CUSTOM_TRIPLET
      color: [255, 255, 255]
    LEFT_LUNG:
      name: custom label and color for lung
      category: C_BODY_STRUCTURE
      type: T_LUNG
      modifier: M_LEFT
      color: [255, 0, 0]

```
